# Causes
Cause.create(id: 23, name: "Advocacy & Human Rights")
Cause.create(id: 30, name: "Animals")
Cause.create(id: 34, name: "Arts & Culture")
Cause.create(id: 38, name: "Board Development")
Cause.create(id: 22, name: "Children & Youth")
Cause.create(id: 25, name: "Community")
Cause.create(id: 37, name: "Computers & Technology")
Cause.create(id: 14, name: "Crisis Support")
Cause.create(id: 17, name: "Disabled")
Cause.create(id: 42, name: "Disaster Relief")
Cause.create(id: 15, name: "Education & Literacy")
Cause.create(id: 28, name: "Emergency & Safety")
Cause.create(id: 27, name: "Employment")
Cause.create(id: 13, name: "Environment")
Cause.create(id: 31, name: "LGBT")
Cause.create(id: 11, name: "Health & Medicine")
Cause.create(id: 7, name: "Homeless & Housing")
Cause.create(id: 39, name: "Hunger")
Cause.create(id: 41, name: "Immigrants & Refugees")
Cause.create(id: 29, name: "International")
Cause.create(id: 5, name: "Justice & Legal")
Cause.create(id: 40, name: "Media & Broadcasting")
Cause.create(id: 6, name: "Politics")
Cause.create(id: 33, name: "Race & Ethnicity")
Cause.create(id: 36, name: "Religion")
Cause.create(id: 12, name: "Seniors")
Cause.create(id: 19, name: "Sports & Recreation")
Cause.create(id: 43, name: "Veterans & Military Families")
Cause.create(id: 3, name: "Women")

# Test events
Event.create(title: "Save Our Government", organization: "People's Public", start: "2016-12-08 10:00:00", end: "2016-12-08 12:00:00", description: "Join us in changing the world.", address: "1 broadway New York, NY 10001", skills_needed: "organizational", minimum_age: 16, url: "www.google.com", cause_id: 23)
Event.create(title: "Water the Plants", organization: "Healthy Group", start: "2016-12-12 13:00:00", end: "2016-12-12 15:00:00", description: "Let's fix this damn thing.", address: "11 broadway New York, NY 10011", skills_needed: "respect", minimum_age: 18, url: "www.amazon.com", cause_id: 23)
Event.create(title: "Hackathonamania", organization: "Flatiron School", start: "2016-12-20 09:00:00", end: "2016-12-20 10:30:00", description: "Build great products.", address: "13 broadway New York, NY 10011", skills_needed: "coding skills", minimum_age: 21, url: "www.netflix.com", cause_id: 23)
Event.create(title: "Guy Kawasaki Free Seminar", organization: "Flatiron School", start: "2016-12-29 09:00:00", end: "2016-12-29 12:30:00", description: "Art of the start seminar.", address: "13 broadway New York, NY 10011", skills_needed: "l33t abilities", minimum_age: 10, url: "www.flatironschool.com", cause_id: 23)
Event.create(title: "Guy Kawasaki Free Seminar 2", organization: "Flatiron School", start: "2016-12-30 10:30:00", end: "2016-12-30 12:00:00", description: "Art of the start seminar TWO.", address: "13 broadway New York, NY 10011", skills_needed: "l33t abilities", minimum_age: 10, url: "www.flatironschool.com", cause_id: 23)
Event.create(title: "Freedom Pups Galore!", organization: "Petco", start: "2016-11-30 09:30:00", end: "2016-11-30 11:30:00", description: "Come and cheer up a pup! Even adopt one!", address: "1 Petlandia Way, New York, NY 10001", skills_needed: "Love, care, and awesomeness.", minimum_age: 5, url: "www.petco.com", cause_id: 30)
